name: BlockWarp
main: com.example.blockwarp.BlockWarpPlugin
version: 1.0.0
api-version: 1.20
description: "Teleport players when they right-click configured blocks"
authors: [ "YourName" ]
commands:
  setwarp:
    description: Create or update a warp at your current location
    usage: /setwarp <name>
    permission: blockwarp.setwarp
  warp:
    description: Warp to a named warp
    usage: /warp <name>
    permission: blockwarp.warp
  linkblock:
    description: Link the block you are looking at to a warp (sneak + right-click with stick)
    usage: /linkblock <warp>
    permission: blockwarp.linkblock
permissions:
  blockwarp.setwarp:
    description: Create or edit warps
    default: op
  blockwarp.warp:
    description: Use /warp and linked blocks
    default: true
  blockwarp.linkblock:
    description: Link a block to a warp
    default: op
